name: Pip.Services AWS toolkit in Go

on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  ci:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main
  
    ############# Prepare #############

    - name: Install prereq and save build number
      id: build_info
      uses: pip-devops/actions/go/prepare@v1

    ############# Test #############

    - name: Test the component
      uses: pip-devops/actions/go/test@v1

    ############# Release #############

    - name: Delete existing tag
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        delete_release: true
        tag_name: "v${{ steps.build_info.outputs.component_version }}-${{ steps.build_info.outputs.build_number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag with the build number
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v${{ steps.build_info.outputs.component_version }}-${{ steps.build_info.outputs.build_number }}"

    ############# Clear #############

    - name: Clean up
      uses: pip-devops/actions/go/clear@v1

  metrics:
    needs: ci
    if: always()
    runs-on: ubuntu-18.04

    steps: 
    ############# Send pipeline metrics #############

    - name: Send pipeline metrics
      uses: pip-devops/actions/pipeline-metrics@v1
      with:
        pipeline-organization: $(echo '${{ github.repository }}' | awk -F '/' '{print $1}')
        pipeline-name: $(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
